name: Python application

# run on comitting (pushing)
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Installing pip and pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: pytest
